name: Build Extension

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create extension zip
        run: |
          mkdir -p build

          zip -r build/HPCRender.zip extension \
            -x "*.git*" \
            -x "__pycache__/*" \
            -x "*.pyc"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HPCRender
          path: build/HPCRender.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/HPCRender.zip
