name: Build Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create extension zip
        run: |
          mkdir -p build

          zip -r build/HPCRender.zip extension \
            -x "*.git*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x "*.DS_Store"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/HPCRender.zip